class WelcomeScene {
	private String title, welcomeText, asteroidNavText, spacebarNavText, escNavText;
	private PShape miniLogo;

	WelcomeScene() {
		title = "WELCOME";
		welcomeText = "Each comet and asteroid that approaches Earth tells a different story through attributes like speed, size, and orientation.\n\nSome are even potentially hazardous to our planet.\n\nThis is a chance to hear the stories generated by today’s feed of Near Earth Objects from NASA.";
		asteroidNavText = "There are [8] bodies currently present around Earth.\nPress [1] through [8] on your keyboard to move between them.";
		spacebarNavText = "PRESS SPACEBAR TO CONTINUE";
		escNavText = "OR ESC TO EXIT";

		miniLogo = loadShape("mini_logo.svg");
	}

	public void update() {
		// The Intro Scene is static
	}

	public void draw() {
		// draw logo
		shape( miniLogo, calculateXForItemAt(364), calculateYForItemAt(113) );

		// draw title
		textAlign(LEFT, TOP);
		textFont(largeFont);
		fill(brightGreen);
		text( title, calculateXForItemAt(463), calculateYForItemAt(125) );

		// draw welcomeText
		textFont(medFont);
		// the second two values are a second x and y (width and height)
		// to wrap text in box
		text( welcomeText, calculateXForItemAt(463), calculateYForItemAt(265), calculateXForItemAt(1108), calculateYForItemAt(343) );

		// draw asteroid nav text
		text( asteroidNavText, calculateXForItemAt(463), calculateYForItemAt(677), calculateXForItemAt(1108), calculateYForItemAt(98) );

		// draw basic nav
		fill(brightGreen);
		text( spacebarNavText, calculateXForItemAt(463), calculateYForItemAt(901) );
		fill(darkGreen);
		text( escNavText, calculateXForItemAt(463), calculateYForItemAt(950) );
	}
}
